MyWaterMonitoringProj/config/routes.rb
Rails.application.routes.draw do
  get 'waterlevels/index' => 'waterlevels#index'
  get 'waterdatas/index'

  get 'waterdatas/import'

  get 'company/index' => 'company#index'

  get 'com_man/index' => 'com_man#index'

  get 'signup' => 'users#new'

  #get 'admin/index'

  #get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'govt/index' => 'govt#index'


  resources :users
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  root 'admin#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MyWaterMonitoringProj/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyWaterMonitoringProj/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_create :confirmation_token

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
  end

  private

  def confirmation_token
    if confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

MyWaterMonitoringProj/app/models/water_level.rb
class WaterLevel < ApplicationRecord
end

MyWaterMonitoringProj/app/models/waterdatum.rb
class Waterdatum < ApplicationRecord
end

MyWaterMonitoringProj/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

MyWaterMonitoringProj/app/controllers/com_man_controller.rb
class ComManController < ApplicationController
  def index
  end
end

MyWaterMonitoringProj/app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
end

MyWaterMonitoringProj/app/controllers/govt_controller.rb
class GovtController < ApplicationController
  def index
  end
  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: "Successfully logged out"
  end
end

MyWaterMonitoringProj/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      if user.email_confirmed
      session[:user_id] = user.id
      case user.user_type
      when 'GOVT'
        redirect_to govt_index_url, notice: "GOVT user's page"
      when 'COMMON-USER'
        redirect_to com_man_index_url, notice: "COMMON user's page"
      when 'PHARMA-COMPANY'
        redirect_to company_index_url, notice: "COMPANY user's page"
      end
      else
        redirect_to login_url, alert: 'Please activate your account by following
the instructions in the account confirmation email you received to proceed'
      end
    else
      redirect_to login_url, alert: 'Invalid user name or password'
    end
  end

  def destroy
    User.find(session[:user_id])
    session[:user_id] = nil
    redirect_to login_url, alert: 'Successfully logged out'
  end
end

MyWaterMonitoringProj/app/controllers/users_controller.rb
    class UsersController < ApplicationController
      skip_before_action :authorize
      before_action :set_user, only: [:show, :edit, :update, :destroy]

      # GET /users
      # GET /users.json
      def index
        @users = User.all
      end

      # GET /users/1
      # GET /users/1.json
      def show; end

      # GET /users/new
      def new
        @user = User.new
      end

      # GET /users/1/edit
      def edit; end

      # POST /users
      # POST /users.json
      # @return [Object]
      def create
        @user = User.new(user_params)
        if User.exists?(email: @user.email)
          redirect_to login_url, alert: 'User already exists!'
          else
          respond_to do |format|
          if @user.save
            UserMailer.welcome_email(@user).deliver_now
            format.html do
              redirect_to login_url, notice: 'User was successfully created.Please confirm your email address to continue'
            end
            format.json { render :show, status: :created, location: @user }
          else
            format.html do
              redirect_to login_url, alert: 'Something went wrong!'
            end
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
        end
        end
      # PATCH/PUT /users/1
      # PATCH/PUT /users/1.json
      # @return [Object]
      def update
        respond_to do |format|
          if @user.update(user_params)
            format.html do
              redirect_to users_url, notice: 'User was successfully updated.'
            end
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { render :edit }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /users/1
      # DELETE /users/1.json
      def destroy
        @user.destroy
        respond_to do |format|
          format.html do
            redirect_to users_url, notice: 'User was successfully destroyed.'
          end
          format.json { head :no_content }
        end
      end

      def confirm_email
        user = User.find_by_confirm_token(params[:id])
        if user
          user.email_activate
          flash[:success] = "Welcome to the Sample App! Your email has been confirmed.
          Please sign in to continue."
          redirect_to login_url
        else
          flash[:error] = 'Sorry. User does not exist'
          redirect_to root_url
        end
      end

      private

        # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

        # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:name, :password, :password_confirmation, :user_type, :mobile_number, :email)
      end

    end

MyWaterMonitoringProj/app/controllers/waterdatas_controller.rb
class WaterdatasController < ApplicationController
  def index
  end
end

MyWaterMonitoringProj/app/helpers/_waterlevels_helper.rb
module WaterlevelsHelper
end

MyWaterMonitoringProj/app/helpers/admin_helper.rb
module AdminHelper
end

MyWaterMonitoringProj/app/helpers/application_helper.rb
module ApplicationHelper
end

MyWaterMonitoringProj/app/helpers/com_man_helper.rb
module ComManHelper
end

MyWaterMonitoringProj/app/helpers/company_helper.rb
module CompanyHelper
end

MyWaterMonitoringProj/app/helpers/govt_helper.rb
module GovtHelper
end

MyWaterMonitoringProj/app/helpers/sessions_helper.rb
module SessionsHelper
end

MyWaterMonitoringProj/app/helpers/users_helper.rb
module UsersHelper
end

MyWaterMonitoringProj/app/helpers/waterdatas_helper.rb
module WaterdatasHelper
end

MyWaterMonitoringProj/app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

MyWaterMonitoringProj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Water Monitoring and Flood Detection Report</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>
<header id="header" class="water-navbar navbar">
  <h1>Water Monitoring and Flood Detection Report</h1>
  <%=	 link_to "Log out", logout_url, { :style => "color :white" }%>
</header>
<div class="container">
  <div class="container-fluid">
    <div id="water-body">
      <% if flash[:notice]  %>
        <div role="alert" class="alert alert-success alert-dismissible fade show">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <% if flash[:alert]  %>
        <div role="alert" class="alert alert-danger alert-dismissible fade show">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

<footer id="footer" class="water-footer">
    <p>footer</p>
</footer>
</body>
</html>